apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata: 
  name: guestbook-git-dir
spec: 
  generators: 
    - 
      git: 
        directories: 
          - 
            path: guestbook-helm/*
        repoURL: "https://github.com/anusree-mmlab/argo-application-set-demo.git"
        revision: HEAD
  template: 
    metadata: 
      name: "{{path.basename}}"
    spec: 
      destination: 
        namespace: "{{path.basename}}"
        server: "https://kubernetes.default.svc"
      project: default
      source: 
        path: "{{path}}"
        repoURL: "https://github.com/anusree-mmlab/argo-application-set-demo.git"
        targetRevision: HEAD
      syncPolicy: 
        automated: 
          prune: true
          selfHeal: true
        syncOptions: 
          - CreateNamespace=true