apiVersion: apps/v1
kind: Deployment
metadata:
  name: guest-sample
  labels:
    app: guest-sample
    chart:  helm-guestbook
    release: helm-guestbook
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guest-sample
      release: helm-guestbook
  template:
    metadata:
      labels:
        app: guest-sample
        release: helm-guestbook
    spec:
      containers:
        - name: helm-guestbook
          image: "gcr.io/heptio-images/ks-guestbook-demo:0.1"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8086
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: 8086
          readinessProbe:
            httpGet:
              path: /
              port: 8086