apiVersion: apps/v1
kind: Deployment
metadata:
  name: guest-sample
  labels:
    app: guest-sample
    chart:  helm-guestbook
    release: helm-guestbook
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guest-sample
      release: helm-guestbook
  template:
    metadata:
      labels:
        app: guest-sample
        release: helm-guestbook
    spec:
      containers:
        - name: helm-guestbook
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8086
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: 8086
          readinessProbe:
            httpGet:
              path: /
              port: 8086